[package]
name = "rust_file_division"
version = "0.1.0"
authors = ["toshinomi <tatsuya.oshinomi.0828@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
